# Generated by Django 5.0.6 on 2024-07-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_country_code_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country_code',
            field=models.CharField(default='1', max_length=5),
        ),
    ]
