# Generated by Django 5.0.6 on 2024-07-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='country_code',
        ),
    ]
