# Generated by Django 5.0.6 on 2024-07-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
